version: '3.8'
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://192.168.5.142:3100/api/prom/push'

services:
  ocelot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocelot_api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80" 
      - "5443:443" # Exposes Ocelot API gateway on port 5000
    volumes:
      - ./ocelot.json:/app/ocelot.json  # Mount Ocelot configuration file
    networks:
      - ocelot_network
    logging: *default-logging  

networks:
   ocelot_network:
       driver: bridge