apiVersion: 1
datasources:
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    readOnly: false
    editable: true
  
  # - uid: prometheus
  #   orgId: 2
  #   name: Prometheus
  #   type: prometheus
  #   typeName: prometheus
  #   access: proxy
  #   url: http://prometheus:9090
  #   password: ''
  #   user: ''
  #   database: ''
  #   basicAuth: false
  #   isDefault: false
  #   readOnly: false
  #   editable: true
  