x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-storage:/loki
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki-grafana-net
    
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9099:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - loki-grafana-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9094:9093"
    networks:
      - loki-grafana-net
  
  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - '9115:9115'
    restart: unless-stopped
    networks:
      - loki-grafana-net

  

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - loki-grafana-net
    logging: *default-logging
  
networks:
  loki-grafana-net:
    driver: bridge

volumes:
  prometheus-data:

