global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:  
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9099']
  
  - job_name: 'cpustats'
    static_configs:
      - targets: ['192.168.5.142:8142', '192.168.5.145:8142']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] # Default module
    static_configs:
      - targets:
          - http://192.168.5.142:5001/api/v1/applicant/Ping
          - http://192.168.5.142:5002/swagger/index.html
          - http://192.168.5.142:5003/api/v1/auth/Ping
          - http://192.168.5.142:5004/swagger/index.html
          - http://192.168.5.142:5005/api/v1/sponsor/Ping # Replace with your target URL
          - http://192.168.5.142:8142/metrics
          - http://192.168.5.145:5001/api/v1/applicant/Ping
          - http://192.168.5.145:5002/swagger/index.html
          - http://192.168.5.145:5003/api/v1/auth/Ping
          - http://192.168.5.145:5004/swagger/index.html
          - http://192.168.5.145:5005/api/v1/sponsor/Ping # Replace with your target URL
          - http://192.168.5.145:8142/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Docker container name

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'