route:
  receiver: 'email-receiver'
  group_wait: 5s            # Wait before sending the first notification
  group_interval: 5m         # Wait 5 minutes before grouping notifications
  repeat_interval: 5m 

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'aksingh.bellurbis@contecglobal.com'
        from: 'aksingh.bellurbis@contecglobal.com'
        smarthost: 'smtp.gmail.com:587' # Use Gmail's SMTP server
        auth_username: 'aksingh.bellurbis@contecglobal.com' # Your Gmail address
        auth_password: 'kmge vcrb aqht xmgg' # Google App Password
        require_tls: true
